- consul/base.py
- consul/twisted.py
- requirements.txt
- tests/test_aio.py
- tests/test_std.py
- tests/test_tornado.py
- tests/test_twisted.py
As python 2.7 is no longer supported, remove usage of six library that was used for retro compatibility.
It makes the code cleaner will allow to remove this dependency
> [cleanup] Remove six dependency

- consul/aio.py
- tests/test_aio.py
The close coroutine was not returned hence it was never scheduled, which create warning like this:
`py-consul/consul/aio.py:45: RuntimeWarning: coroutine 'ClientSession.close' was never awaited`
> Fixed async to correctly close http session

- consul/aio.py
These features were historically used internally by monkey patching the lib in a not-so-pleasant way.
Proposing to align the open-source repository regarding these features on the aiohttp implementation (so that we can remove our specifics):
* correct support for client certificate
* connections limit override
* session timeout override
> Consul aiohttp features backport

- consul/aio.py
There was an impossible test, so timeout was ignored.
> aio: fix timeout support

- README.rst
This breaks twine upload as macros are no more defined.
As a consequence, remove sections with dead macros.
> fix README rendering

- consul/base.py
As of consul 1.3.0 api supports multiple tags.
Did not want to break backwards compatibility, so I did not change the param and made it possible to use string as in the past or a list for multiple tag params.
> feature: allow multiple tags in service health query

- consul/aio.py
aiohttp expects a ClientTimeout object, not an integer.
> aio: fix timeout type

- consul/base.py
Namely:
* /v1/agent/maintenance
* /v1/agent/join
* /v1/agent/service/deregister
* /v1/agent/service/maintenance
* /v1/agent/check/deregister
* /v1/agent/check/pass
* /v1/agent/check/warn
* /v1/agent/check/fail
Reused the existing pattern, ie. tries to fetch it from the agent object,
or use the one passed in argument.
> Add token support missing in multiple methods

- consul/base.py
These endpoints were missing in order to provide access to Connect-related
endpoints:
* /v1/connect/ca/roots
* /v1/connect/ca/configuration
* /v1/service/connect/:service
* /v1/health/connect/:service
* /v1/agent/connect/authorize
* /v1/agent/connect/ca/roots
* /v1/agent/connect/ca/leaf/:service
Some of them such as /service/connect and /health/connect were integrated
using factorization since their in/out signature is exactly the same.
> Introduce Consul Connect-related API wrappers

- consul/base.py
This was previously not introduced most probably because it breaks the general assumption that this wrapper will preserve the API namespacing, while here we have a collision between this endpoint (/v1/agent/service/:service_id) and the methods to register/deregister/add to maintenance (/v1/agent/service/register for example).
Solved this by changing the naming to "service_definition".
> Add support for agent/service/:service_id API

- consul/aio.py
- consul/base.py
- consul/std.py
- consul/tornado.py
- consul/twisted.py
- tests/test_base.py
To prevent any occurrence of conflicts between the Connect object that wraps Consul-Connect related APIs and the internal methods to setup the HTTP Client.
This is marked as breaking since each home-made implementation for a http client will have to rename its `connect` function into `http_connect`.
> bugfix: rename internal connect method

- consul/base.py
- consul/std.py
- consul/tornado.py
- consul/twisted.py
By implementing (a)enter/(a)exit internal methods, we bring the support for context-managers in the base.Consul object.
Context managers are quite convenient, especially for the aio implementation in which you may need a good control over objects lifecycle to prevent errors related to already-closed event loops:
This is done by forcing http implementations to define a close method and defining the (a)enter/(a)exit internal methods.
Most of the synchronous implementations will use a noop.
```
async with aio.Consul(...) as consul:
svcs = consul.agent.services()
```
> Add support for context-managers

- CHANGELOG.rst
- consul/__init__.py
- consul/base.py
In be07afd ("Introduce Consul Connect-related API wrappers")
multiple endpoint callbacks were associated to the wrong callback
type, resulting in boolean results where json payload is expected.
> connect: fix wrong endpoints callbacks

- consul/base.py
Prevent returning a tuple upon 404 and honor index parameter instead.
> base: ensure return format of json callback is more consistent

- consul/base.py
- tests/test_std.py
Without breaking compatibility, an optional extra_checks list of Checks allows us to register multiple checks during service registration.
Note that this was still possible through check registration but requires multiple API calls.
Also extended a test to register multiple checks and ensure both are passing
> Service registration with multiple checks

- tests/conftest.py
- tests/test_aio.py
- tests/test_base.py
- tests/test_std.py
This PR introduces multi-version tests.
Due to the fact that tests were running on consul 1.1.0,
some tests have been temporarily disabled due to
issues with newer API.
Will be fixed upcoming PRs dropping consul 1.1.0 support
> tests: multi consul version tests

- CHANGELOG.rst
- MANIFEST.in
- consul/__init__.py
- pyproject.toml
- setup.py
Change log
==========
1.4.0
-----
* feature: re-implement some basic ACL endpoint
* feature: drop support of OSX and consul 1.1.0
* feature: support multi-check service registration (through extra_checks parameter)
* env: support python 3.12
* tests: multi consul version test (1.13.8, 1.15.4, 1.16.1, 1.17.3)
* tests: add test utils for cleaner API output expected assertion
* code-style: use ruff linter and formatter
* code-style: split files following the consul API logic
* ci: speedup ci with uv/tox-uv
> Release 1.4.0

- README.md
update README following fork detach and project move
> docs: update README following fork detach and project move

- tests/api/test_acl.py
- tests/conftest.py
- tests/test_aio.py
This change is made in preparation for future releases, anticipating the likelihood of deploying multiple instances via Docker.
> Refactor acl_consul fixture

- consul/api/acl.py
- consul/api/acl/__init__.py
- consul/api/acl/policy.py
- consul/api/acl/token.py
- tests/api/test_acl.py
Refactor consul.acl 
move token to consul.acl.token 
create  consul.acl.policies
> Introduce policy list/read capabilities

- .github/workflows/main.yml
- .github/workflows/tagged_release.yml
The main workflow now has an appropriate name and the fail-fast strategy is disabled, allowing linting and testing steps to continue on each python version.
The tagged release workflow do not run linters and tets anymore.
> ci: update github actions

- consul/api/acl/policy.py
- consul/api/acl/token.py
- Implement creation of policies.
- Integrate policy addition during token creation.
> Enhance Token Creation with Policy Support

- consul/api/agent.py
By default the requests to the Agent.force_leave method does not pass any authorization token. On a cluster that requires authorization, this means that you can not remove dead nodes from the client library. This PR should resolve that by passing the token param the same as the other methods do.
> Add token authorization to Agent.force_leave

- conftest.py
- pyproject.toml
- setup.py
- tests-requirements.txt
- tests/api/test_agent.py
- tests/api/test_health.py
- tests/conftest.py
- tests/test_aio.py
- tests/test_base.py
Drop support for 1.13 and 1.15 (partially for convenience as
they're not in the hashicorp docker repo).
We now also capture container logs and store them in a logs/
folder. Each test will have its own consul log file.
This required a conftest.py split, where Consul agent creation fixture remain in the tests/ folder
to avoid cyclic import, while all the other parts are moved to the uppermost folder.
A few linter changes required due to a ruff upgrade.
An old deprecated setuptools test feature has been removed too.
Fixed some flakiness by increasing a few sleeps. HTTP checks also have a minimal timeout of 1s hardcoded into consul.
> Test using consul container instead of plain binaries stored in the repo

- conftest.py
- consul/aio.py
- consul/api/acl/policy.py
- consul/api/acl/token.py
- consul/api/agent.py
- consul/api/catalog.py
- consul/api/connect.py
- consul/api/event.py
- consul/api/health.py
- consul/api/kv.py
- consul/api/query.py
- consul/base.py
- consul/std.py
- tests/test_base.py
Fix a pretty rare docker start flakyness by retrying a few times if required.
?token=<token> query param is deprecated. It should have been removed in consul 1.17.
While it's still properly handled as of 1.18 at least, we should now use X-Consul-Token header
This overrides a previous PR https://github.com/criteo/py-consul/pull/51
> Replace deprecated token query param by X-Consul-Token header 

- consul/api/catalog.py
- pyproject.toml
- Introduced `replace_existing_checks` parameter in the `register()` method to allow deletion of missing health checks from the request.
- Ensures idempotent registration of services and their checks without needing manual deregistration of checks.
> feat: add replace_existing_checks option to Catalog.register()

- CHANGELOG.md
- consul/__init__.py
- consul/api/agent.py
- consul/api/catalog.py
Move replace_existing_checks from Catalog.register() to agent.service.register()
> feat: add replace_existing_checks option to agent.service.register()

- consul/base.py
- tests/test_base.py
Currently, the `host`, `port`, `verify`, and `scheme` arguments get ignored on initialization if an environment variable is set. This adds support for overriding the environment variables.
> Add support for honoring additional arguments in consul.Consul()

- CHANGELOG.md
- consul/__init__.py
- consul/callback.py
If JSON decoding fails, if a field is missing, or if there are no fields, a ConsulException is returned.
> Improve robustness of JSON decoding

- CHANGELOG.md
- consul/__init__.py
- consul/aio.py
- docs/index.rst
- Align with aiohttp's BaseConnector pattern of using `loop = loop or asyncio.get_running_loop()`
- Remove redundant loop retrieval logic
- Use `asyncio.get_running_loop()` instead of deprecated `asyncio.get_event_loop()`
- Update documentation example to use `asyncio.get_running_loop()`
> Simplify loop handling in async Consul client

- .pre-commit-config.yaml
- README.md
- conftest.py
- consul/aio.py
- consul/api/acl/token.py
- consul/base.py
- consul/std.py
- pyproject.toml
Drop 1.16 and support versions up to 1.20 (latest)
Use python3.9 as the default for linters.
[[chore] migrate pre-commit config](https://github.com/criteo/py-consul/commit/a18e79ac62ff2bfd8651c1ccc01f31ad4dffa352)
[[chore] Update linter default python version](https://github.com/criteo/py-consul/commit/14caa312025b13fa449c9df0c5de4875db16653f)
[Bump supported consul version (1.17 -> 1.20)](https://github.com/criteo/py-consul/commit/cf857a674578f6427fdc6bac1abe6359d2a74f8f)
Closes https://github.com/criteo/py-consul/issues/94
> Consul 1.20 support
